# Configuration for Upptime 
owner: OmniFuse
repo: uptime

sites:
  - name: ChatAll API
    url: https://api.chatall.ru
  - name: ChatAll
    url: https://chatall.ru

status-website:
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ChatAll Status
  introTitle: "**ChatAll Status** - System uptime monitoring"
  introMessage: This page displays real-time status information for ChatAll services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/OmniFuse/uptime

# Optional settings that you might want to add:
# assignees:
#   - YourGitHubUsername
# 
# notifications:
#   - type: email
#     notification_email: your-email@example.com
# 
# commitMessages:
#   readmeContent: "📝 Update status summary"
#   summaryJson: "🔄 Update status summary"
#   statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
#   graphsUpdate: "📊 Update graphs"
